default_language_version:
  # default language version for each language
  python: python3.8
repos:
  -   repo: https://github.com/ambv/black
      rev: 23.3.0
      hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
        exclude: tests/
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: tests/test_changes/
        files: \.(py|sh|rst|yml|yaml)$
      - id: mixed-line-ending
      - id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
            'flake8-blind-except',
            'flake8-docstrings',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
            'flake8-implicit-str-concat',
            'pydocstyle',
            'flake8-coding',
            'flake8-debugger',
            'flake8-deprecated',
            'flake8-isort',
            'flake8-pep3101',
            'flake8-polyfill',
            'flake8-print',
            'flake8-quotes',
            'flake8-string-format',
        ]
        exclude: ^tests/test_cases/no_closing_bracket\.py$
  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.1.1
    hooks:
      - id: rstcheck
        args: [
            --report-level=warning,
        ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        files: \.(py|sh|rst|yml|yaml)$
